### ISSUE TITLE
How do you install this Software???

### ISSUE THREAD

**Issue by marty121412** [sandialabs/NuMAD#16]
I have a windows x64 I cannot for the life of me to work out how to install this software please help? 
I have ANSYS & MATLAB downloaded onto my machine.

**Comment by ecamare** [comment]
Hi Marty, Sorry to hear the trouble. Have you followed the directions on our documentation [()?](https://numad.readthedocs.io/en/latest/user/getting_started.html#install-numad) If so, what step are you on? In general, there are two ways to install it. One way is to "clone" the repository with Git and the other is a direct download of the Matlab files.

**Comment by rclarke17** [comment]
Hi Marty,
NuMAD v3.0 has new documentation which can be found in the link below.
http://numad.readthedocs.io/

**Comment by marty121412** [comment]
Thanks Ryan I'll check it out

Kind regards,

Marty
________________________________

**Comment by ecamare** [comment]
Hi Marty, 

No, I did not send you a link for NuMAD 2.0. The link I provided was is for NuMAD 3.0. Ryan's link is for the documentation in general. My link points you to the installation portion specifically.

Best,
Ernesto

**Comment by marty121412** [comment]
Hi Ernesto,

The link you sent looks like just what I'm after thanking you for your assistance.

Kind regards,

Marty
________________________________

**Comment by GncDude** [comment]
Hello Sir/s, I cant setup. I am sorry I couldnt not understand… I have student edu Ansys and Matlab, anaconda and python and visualstudio. Mat you show us setup tutorial video please? Please :( King Regards
