### ISSUE TITLE
problem about NuMAD v2

### ISSUE THREAD

**Issue by ali-rouhbakhsh** [sandialabs/NuMAD#17]
when i try to open a simple model this error occured:

Error using cell2mat (line 52)
CELL2MAT does not support cell arrays containing cell arrays or objects.

Error in NuMAD_main>loadmodel (line 911)
    set(cell2mat(app.smdp.hg_sm),'Visible','off');

Error in NuMAD_main>openmodel (line 815)
    loadmodel(cbo,[]);  % finish loading required data and display model

Error in NuMAD_main>cb_openmodel (line 725)
        openmodel(pn,fn,cbo);
 
Error while evaluating Menu Callback.

**Comment by ecamare** [comment]
Sorry for the delay. Is this still a problem for you? How are you trying to open it?

**Comment by ali-rouhbakhsh** [comment]
Yes, I still have a problem
After I installed NuMAD, I opened it through MATLAB and from the open model section, I tried to open one of the sample models included by the software called SNLWindPACTv1.3.

**Comment by rclarke17** [comment]
have you copied the file txt2mat.m to your MATLAB search path?

**Comment by kercc1985** [comment]
txt2mat.m is in my  MATLAB search path，but I still have a same problem. 
"CELL2MAT does not support cell arrays containing cell arrays or objects."
