### ISSUE TITLE
How can the numad 3.0 be used without guide book?

### ISSUE THREAD

**Issue by moonstar123456** [sandialabs/NuMAD#33]
There is only guide book for Numad 2.0, but no guide information for 3.0. 

I have two questions:

1. how can the 3.0 be used with graphic interface as 2.0?
2. Without graphic interface , how can the 3.0 be used in Matlab? Where can check the application's commands for 3.0?

Much appreciated for everyone's help!

**Comment by kbonney** [comment]
Hello @moonstar123456,
Version 3.0 of NuMAD does not use the graphics interface. To get started with 3.0 please refer to the [examples](https://numad.readthedocs.io/en/latest/user/examples.html). If you have any specific questions about the use of NuMAD 3.0, feel free to open another issue.
