### ISSUE TITLE
Error when running "IECOutput = runIEC(DLCoptions,simFlag,IEC)"

### ISSUE THREAD

**Issue by namnguyen-lqdtu** [sandialabs/NuMAD#36]
In the script "NuMAD\examples\runIEC\IECLoadsAnalysis.m", an error shows up when running the following line:
IECOutput = runIEC(DLCoptions,simFlag,IEC);

![runICE_error](https://github.com/sandialabs/NuMAD/assets/84730230/746c9869-fa7b-4893-b248-888590a34c15)

What I have to input here?

**Comment by kbonney** [comment]
This issue is being discussed in issue #37.
