### ISSUE TITLE
is it possible to have help file for numad 3.0?

### ISSUE THREAD

**Issue by moonstar123456** [sandialabs/NuMAD#41]
Dear All,
1. is it possible to have help file for numad 3.0? where can get the help file for numad 3.0?
2.  how to install numad 3.0?
3. is it possible to use the graphic window for numad 3.0 as the same as numad 2.0?

Much apprecited for all you help!

**Comment by ecamare** [comment]
You can find help in our [documentation](https://numad.readthedocs.io/en/latest/).

There you will also find installation instructions. Yes, you can use the graphics window in numad 3.0. Check 

https://numad.readthedocs.io/en/latest/user/operation_modes.html#numad-gui-mode

 for more info.
