### ISSUE TITLE
Is it possible to publish a user guide for numad 3.0? 

### ISSUE THREAD

**Issue by moonstar123456** [sandialabs/NuMAD#48]
Dear leader of numad 3.0， Is it possible to publish an user guide for numad 3.0? i really don't know how to use numad 3.0 according to the user guide for numad 2.0. Thank you very much!
 The numad 2.0 can't deal with blade of  10MW or 16MW ? only can deal with the blade of 5MW, right?

**Comment by rclarke17** [comment]
We have a getting started guide, and some explanations about NuMAD 3.0 here: https://numad.readthedocs.io/en/latest/
