### ISSUE TITLE
How to generate aerodyne input file in .ipt format

### ISSUE THREAD

**Issue by rajkishore1121** [sandialabs/NuMAD#9]
can you please tell me the procedure to generate Aerodyn input file.

**Comment by ecamare** [comment]
Hi, the best we can offer you is the example Aerodyn input file located here: 

[https://github.com/sandialabs/NuMAD/blob/main/examples/runIEC/exampleAeroDyn.ipt](url)

I am sorry we could not be more helpful. 

NuMAD does not currently make an AeroDyn input file. You could consider adding this functionality with a pull-request.
